from premia._shared import PremiaError


class DataError(PremiaError):
    """Custom exception class for data related errors."""

    pass
